# Generated by Django 3.2.5 on 2022-01-05 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_url', models.CharField(max_length=255)),
                ('consult_date', models.DateTimeField(default=False)),
                ('product_url_created_at', models.DateTimeField(max_length=255)),
                ('product_url_image', models.CharField(max_length=255)),
                ('store_url', models.CharField(max_length=255)),
                ('c', models.IntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
