# Generated by Django 3.2.5 on 2022-01-06 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_auto_20220105_2053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['pk'], 'verbose_name': 'products', 'verbose_name_plural': 'products'},
        ),
    ]
